INSERT IGNORE INTO users VALUES(1, 'Home', 'https://image.flaticon.com/icons/png/512/25/25694.png')
INSERT IGNORE INTO users VALUES(2, 'Jan K.', 'https://randomuser.me/api/portraits/men/2.jpg')
INSERT IGNORE INTO users VALUES(3, 'Adam N.', 'https://randomuser.me/api/portraits/men/6.jpg')
INSERT IGNORE INTO users VALUES(4, 'Anna K.', 'https://randomuser.me/api/portraits/women/8.jpg')
INSERT IGNORE INTO users VALUES(5, 'Olga O.', 'https://randomuser.me/api/portraits/women/12.jpg')
